"""Constants for IronLogic Z-5R Controller integration."""

DOMAIN = "ironlogic"
CONF_USERNAME = "username"
CONF_AUTH_KEY = "auth_key"
DEFAULT_POLL_INTERVAL = 30
DEFAULT_TIMEOUT = 10

# Defaults
DEFAULT_OPEN_TIME = 3
DEFAULT_COMMAND_COOLDOWN = 3

# Storage
STORAGE_KEY = f"{DOMAIN}.keys"
STORAGE_VERSION = 1

# Event types from controller (Appendix 1)
EVENT_OPENED_BY_BUTTON = 0x00
EVENT_OPENED_BY_BUTTON_EXIT = 0x01
EVENT_KEY_NOT_FOUND = 0x02
EVENT_KEY_NOT_FOUND_EXIT = 0x03
EVENT_KEY_GRANTED = 0x04
EVENT_KEY_GRANTED_EXIT = 0x05
EVENT_KEY_DENIED = 0x06
EVENT_KEY_DENIED_EXIT = 0x07
EVENT_OPENED_BY_NETWORK = 0x08
EVENT_OPENED_BY_NETWORK_EXIT = 0x09
EVENT_KEY_DENIED_DOOR_LOCKED = 0x0A
EVENT_KEY_DENIED_DOOR_LOCKED_EXIT = 0x0B
EVENT_DOOR_TAMPERED = 0x0C
EVENT_DOOR_TAMPERED_EXIT = 0x0D
EVENT_DOOR_LEFT_OPEN = 0x0E
EVENT_DOOR_LEFT_OPEN_EXIT = 0x0F
EVENT_PASSAGE_COMPLETED = 0x10
EVENT_PASSAGE_COMPLETED_EXIT = 0x11
EVENT_SENSOR_1 = 0x12
EVENT_SENSOR_2 = 0x13
EVENT_CONTROLLER_REBOOT = 0x14
EVENT_POWER = 0x15
EVENT_BUTTON_LOCKED = 0x16
EVENT_BUTTON_LOCKED_EXIT = 0x17
EVENT_ANTIPASSBACK_EXIT = 0x1A
EVENT_ANTIPASSBACK_EXIT_ALT = 0x1B
EVENT_LOCK_ON = 0x1C
EVENT_LOCK_ON_EXIT = 0x1D
EVENT_LOCK_OFF = 0x1E
EVENT_LOCK_OFF_EXIT = 0x1F
EVENT_DOOR_OPENED = 0x20
EVENT_DOOR_OPENED_EXIT = 0x21
EVENT_DOOR_CLOSED = 0x22
EVENT_DOOR_CLOSED_EXIT = 0x23
EVENT_POWER_MANAGEMENT = 0x24
EVENT_MODE_CHANGE = 0x25
EVENT_FIRE = 0x26
EVENT_SECURITY = 0x27
EVENT_PASSAGE_NOT_COMPLETED = 0x28
EVENT_PASSAGE_NOT_COMPLETED_EXIT = 0x29
EVENT_GATEWAY_ENTRY = 0x30
EVENT_GATEWAY_ENTRY_EXIT = 0x31
EVENT_GATEWAY_BLOCKED = 0x32
EVENT_GATEWAY_BLOCKED_EXIT = 0x33
EVENT_GATEWAY_ALLOWED = 0x34
EVENT_GATEWAY_ALLOWED_EXIT = 0x35
EVENT_ANTIPASSBACK_BLOCKED = 0x36
EVENT_ANTIPASSBACK_BLOCKED_EXIT = 0x37
EVENT_HOTEL_MODE = 0x40
EVENT_HOTEL_CARD = 0x41
EVENT_CARD_NUMBER = 0x55
EVENT_CARD_NUMBER_7BYTE = 0x56

# Door events (both entry and exit)
DOOR_OPEN_EVENTS = {
    EVENT_DOOR_OPENED,
    EVENT_DOOR_OPENED_EXIT,
    EVENT_DOOR_TAMPERED,
    EVENT_DOOR_TAMPERED_EXIT,
}
DOOR_CLOSED_EVENTS = {EVENT_DOOR_CLOSED, EVENT_DOOR_CLOSED_EXIT}

# Platforms
PLATFORMS = ["lock", "sensor", "binary_sensor", "switch", "number", "button"]
